- name: Lint with flake8
  run: |
    pip install flake8
    flake8 .
- name: Lint with ESLint
  run: |
    npm install
    npx eslint .
- name: Run unit tests with nose
  run: |
    pip install nose
    nosetests
- name: Run unit tests with Jest
  run: |
    npm install
    npx jest
